apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  NACOS_SERVER_ADDR: "nacos.infrastructure:8848"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.infrastructure:9092"
  REDIS_HOST: "redis.infrastructure"
  MYSQL_HOST: "mysql.infrastructure"
  TEMPORAL_HOST: "temporal.infrastructure:7233"
  TEMPORAL_ENABLED: "true"
