apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices

resources:
  - ../../base
  - ../../services/user-service
  - ../../services/order-service
  - ../../services/auth-service
  - ../../services/chat-service

commonLabels:
  environment: development

# 开发环境使用较少副本
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
